"""empty message

Revision ID: 122961a2feb3
Revises: None
Create Date: 2017-04-24 21:43:58.763337

"""

# revision identifiers, used by Alembic.
revision = '122961a2feb3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
