"""empty message

Revision ID: 14f4510a4b9c
Revises: 26a7690d5d20
Create Date: 2016-09-28 22:01:35.764202

"""

# revision identifiers, used by Alembic.
revision = '14f4510a4b9c'
down_revision = '26a7690d5d20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
