"""empty message

Revision ID: 182f4a12e756
Revises: 56a56bb90669
Create Date: 2016-10-08 21:07:58.022987

"""

# revision identifiers, used by Alembic.
revision = '182f4a12e756'
down_revision = '56a56bb90669'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
