"""empty message

Revision ID: 1bb574b92fbd
Revises: 33ffe1bf9bdc
Create Date: 2016-12-20 00:41:56.671402

"""

# revision identifiers, used by Alembic.
revision = '1bb574b92fbd'
down_revision = '33ffe1bf9bdc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'author_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('author_id', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
