"""init migrate

Revision ID: 1eceea737d15
Revises: None
Create Date: 2016-09-24 15:06:26.157701

"""

# revision identifiers, used by Alembic.
revision = '1eceea737d15'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
