"""empty message

Revision ID: 26a7690d5d20
Revises: 2e6c567655af
Create Date: 2016-09-27 22:24:55.149210

"""

# revision identifiers, used by Alembic.
revision = '26a7690d5d20'
down_revision = '2e6c567655af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
