"""empty message

Revision ID: 2876650a0987
Revises: 1bb574b92fbd
Create Date: 2016-12-21 21:26:59.024578

"""

# revision identifiers, used by Alembic.
revision = '2876650a0987'
down_revision = '1bb574b92fbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
