"""empty message

Revision ID: 2acf6b7bd871
Revises: 2d9556b4bf43
Create Date: 2016-09-29 22:39:29.789541

"""

# revision identifiers, used by Alembic.
revision = '2acf6b7bd871'
down_revision = '2d9556b4bf43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
