"""empty message

Revision ID: 2d9556b4bf43
Revises: 46455d34abdd
Create Date: 2016-09-29 20:53:12.261547

"""

# revision identifiers, used by Alembic.
revision = '2d9556b4bf43'
down_revision = '46455d34abdd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
