"""empty message

Revision ID: 2e6c567655af
Revises: 1eceea737d15
Create Date: 2016-09-27 22:12:06.442667

"""

# revision identifiers, used by Alembic.
revision = '2e6c567655af'
down_revision = '1eceea737d15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
