"""empty message

Revision ID: 320e23a29705
Revises: 3de79a23faab
Create Date: 2016-10-02 15:13:13.021726

"""

# revision identifiers, used by Alembic.
revision = '320e23a29705'
down_revision = '3de79a23faab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
