"""empty message

Revision ID: 33ffe1bf9bdc
Revises: 9c9be79258
Create Date: 2016-12-20 00:40:07.908949

"""

# revision identifiers, used by Alembic.
revision = '33ffe1bf9bdc'
down_revision = '9c9be79258'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('author_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'author_id')
    ### end Alembic commands ###
