"""empty message

Revision ID: 359cc4c0b6ea
Revises: 48ae8903a1c6
Create Date: 2016-12-18 15:41:24.671534

"""

# revision identifiers, used by Alembic.
revision = '359cc4c0b6ea'
down_revision = '48ae8903a1c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
