"""empty message

Revision ID: 37faf2cd71ef
Revises: 12d24e4f7e77
Create Date: 2016-10-02 09:37:23.405810

"""

# revision identifiers, used by Alembic.
revision = '37faf2cd71ef'
down_revision = '12d24e4f7e77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
