"""empty message

Revision ID: 3de79a23faab
Revises: 37faf2cd71ef
Create Date: 2016-10-02 09:54:17.806055

"""

# revision identifiers, used by Alembic.
revision = '3de79a23faab'
down_revision = '37faf2cd71ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
