"""empty message

Revision ID: 46455d34abdd
Revises: 14f4510a4b9c
Create Date: 2016-09-28 23:25:43.676427

"""

# revision identifiers, used by Alembic.
revision = '46455d34abdd'
down_revision = '14f4510a4b9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
