"""empty message

Revision ID: 504f7fff35f0
Revises: 3d9ca2e76155
Create Date: 2016-10-02 21:05:59.671201

"""

# revision identifiers, used by Alembic.
revision = '504f7fff35f0'
down_revision = '3d9ca2e76155'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
