"""empty message

Revision ID: 56a56bb90669
Revises: 504f7fff35f0
Create Date: 2016-10-03 10:01:43.119668

"""

# revision identifiers, used by Alembic.
revision = '56a56bb90669'
down_revision = '504f7fff35f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
