"""empty message

Revision ID: 9bc79fc4bf3d
Revises: None
Create Date: 2017-04-25 18:49:17.361963

"""

# revision identifiers, used by Alembic.
revision = '9bc79fc4bf3d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'photos_pkey')
    )
    ### end Alembic commands ###
