"""empty message

Revision ID: 9c9be79258
Revises: 359cc4c0b6ea
Create Date: 2016-12-20 00:36:27.892660

"""

# revision identifiers, used by Alembic.
revision = '9c9be79258'
down_revision = '359cc4c0b6ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    ### end Alembic commands ###
