"""empty message

Revision ID: 9ef2970dad4
Revises: fa9bd251b59
Create Date: 2016-10-01 19:54:08.489478

"""

# revision identifiers, used by Alembic.
revision = '9ef2970dad4'
down_revision = 'fa9bd251b59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
