"""empty message

Revision ID: dde3350521d
Revises: d3f8295ea3e
Create Date: 2016-10-23 15:39:53.420999

"""

# revision identifiers, used by Alembic.
revision = 'dde3350521d'
down_revision = 'd3f8295ea3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
